### ISSUE TITLE
App with no respond and 100% CPU usage

### ISSUE THREAD

**Issue by qinwf** [statsplot/jshinyserver#2]
Hi, I have a shiny app that can not run on jshinyserver. I verified that this app can run on the RStudio version Shiny server.

Here is the source to this shiny app: https://bitbucket.org/qinwf/shiny-rustr/src/cd208d55b4e2/www/?at=master

And here is the Dockerfile of the original one which run on RStudio version Shiny server. https://bitbucket.org/qinwf/shiny-rust-docker/src/9e33a79dfd22f5857b38e31ba52c2e4223772b4a/Dockerfile?at=master&fileviewer=file-view-default 

log files of jshinyserver https://bitbucket.org/snippets/qinwf/G5x9j

**Comment by statsplot** [comment]
Hi,

I get access denied page when downloading the Dockerfile.  Is it the same with https://hub.docker.com/r/qinwf/shiny-rust-docker/  


Can you set loglevel=debug and shiny_sanitize_errors = false in the config file  
I've updated the document: https://github.com/statsplot/jshinyserver/blob/master/documents/production.md#troubleshooting 

Does R communicates directly with Rust?

**Comment by qinwf** [comment]
Sorry, just make it open. https://bitbucket.org/qinwf/shiny-rust-docker/src/9e33a79dfd22f5857b38e31ba52c2e4223772b4a/Dockerfile?at=master&fileviewer=file-view-default

No, no direct call to rust, rustinr is R package, which does not have Rust code. It calls external program rust compiler with `system()`. External program will be run by clicking a button in the shiny apps.

You can see a running example on https://play.rustr.org/ , which is run in RStudio version of Shiny Server.

**Comment by qinwf** [comment]
Here is the docker file for a jshinyserver running this app, https://bitbucket.org/snippets/qinwf/G5xon

You can `docker exec` to check the logs and change log settings.

The logs did not change much with `shiny_sanitize_errors = false`

```bash 
[info]  2016-12-15T02:37:33Z    verifyAppInit    port=10000
[info]  2016-12-15T02:37:34Z    verifyAppInit   Test if the app is running
[info]  2016-12-15T02:37:35Z    startShinySuccess        Shiny app is running
```

```bash
[info]  2016-12-15T02:37:10Z             Server starting ============ ETURN)
TmpDir = /tmp/rshiny
Time = 2016-12-15 02:37:10 UTC
Serverversion = v0.94-beta.4
Java = 1.8.0_111
JavaVendor = Oracle Corporation
JavaRuntime = 1.8.0_111-b14
Processors = 2
System = Linux
Arch = amd64
TotalMemory = 7793
-----config loading-------
rbin = /usr/bin/R
cpulimit2 = 1
cpulimit1 = 1
client_maxidle_timeout = 300
memlimit2 = 6
app_idle_timeout = 100
memlimit1 = 5
shiny_sanitize_errors = false
formmaxsizekb = 3000
lc_all =
pandoc =
port = 8888
redirect_output = true/server_output_2016_12_15_02_37_10.log
wscmaxtextsizekb = 3000
loglevel = debug
htmlroot = shiny
shinyfolder = /opt/shiny/download/master/jshinyserver-master/source/Objects/shin
yapp
r_args = --vanilla
app_init_timeout = 40
wsmaxtextsizekb = 3000
-----config loaded-------
Sys.getlocale=LC_CTYPE=en_US.UTF-8;LC_NUMERIC=C;LC_TIME=en_US.UTF-8;LC_COLLATE=e
n_US.UTF-8;LC_MONETARY=en_US.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=en_US.UTF-8;
LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=en_US.UTF-8;LC_IDENTIFICATI
ON=C
Shiny version=0.14.2
2016-12-15 02:37:11.356:INFO::main: Logging initialized @822ms
2016-12-15 02:37:11.524:INFO:oejs.Server:main: jetty-9.3.z-SNAPSHOT
2016-12-15 02:37:11.654:INFO:oejsh.ContextHandler:main: Started o.e.j.s.ServletC
ontextHandler@47c62251{/,file:///opt/shiny/download/master/jshinyserver-master/s
ource/Objects/www/,AVAILABLE}
2016-12-15 02:37:11.657:INFO:oejs.AbstractNCSARequestLog:main: Opened /opt/shiny
/download/master/jshinyserver-master/source/Objects/logs/b4j-2016_12_15.request.
log
2016-12-15 02:37:11.673:INFO:oejs.ServerConnector:main: Started ServerConnector@c8d8cb4{HTTP/1.1,[http/1.1]}{0.0.0.0:8888}
2016-12-15 02:37:11.674:INFO:oejs.Server:main: Started @1142ms
[info]  2016-12-15T02:37:11Z             Server started ============
[debug] 2016-12-15T02:39:34Z    timercleantmp   clean temp files
```

**Comment by statsplot** [comment]
I can reproduce this issue, working on it

**Comment by statsplot** [comment]
You can test the branch `highcpuload` (change VER=master to VER=highcpuload  in the shell script)

To make language setting work, modify xhr.js  
{return{loadPath:"/locales/{{lng}}/{{ns}}.json"
TO
{return{loadPath:"locales/{{lng}}/{{ns}}.json"

**Comment by qinwf** [comment]
Thanks, it works. https://play.rustr.org is now on jshinyserver.
